services:
  - type: web
    name: vehicle-spruce-frontend
    env: node
    buildCommand: npm install
    startCommand: npm run build && npm run preview
    envVars:
      - key: NODE_OPTIONS
        value: --max_old_space_size=2048